version: "3.8"

services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: compta_db
      MYSQL_USER: compta_user
      MYSQL_PASSWORD: compta_pass
    ports:
      - "3307:3306"
    volumes:
      - ./docker/db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=compta_user
      - PMA_PASSWORD=compta_pass
    ports:
      - "8081:80"
    depends_on:
      - db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: symfony_backend
    volumes:
      - ./backend:/var/www/html
      - ./backend/apache/vhost.conf:/etc/apache2/sites-available/000-default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - db
    command: >
      sh -c "
      composer install &&
      php bin/console doctrine:migrations:migrate --no-interaction &&
      apache2-foreground"

  frontend:
    image: node:20
    container_name: vanilla_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
